TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.05
  max_rotational_vel: 0.6
  min_in_place_rotational_vel: 0.2
  escape_vel: -0.2

  sim_time: 2.0
  path_distance_bias: 0.6
  goal_distance_bias: 0.6

  acc_lim_th: 2.5
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  holonomic_robot: false
