TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.05
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.3
  escape_vel: -0.2

  sim_time: 1.0
  path_distance_bias: 0.6
  goal_distance_bias: 0.6

  acc_lim_th: 2.5
  acc_lim_x: 1.5
  acc_lim_y: 1.5

  holonomic_robot: false
