# Descriptor modifies the names of the published topics
descriptor: "kinect"
enabled: false   # Try setting true

#Sensor Positioning:
x: 0.08       # Meters
y: 0.0        # Meters
height: 0.35  # Meters
pan: 0.0      # Radians
tilt: 0.2     # Radians

#Sensor Settings:
far_clip: 3.0 # Meters
