# Descriptor also modifies the published laser topic.
descriptor: "rear"
enabled: false   # Try setting true
visualize: true

#Sensor Positioning:
x: -0.23    # Meters
y: 0.0      # Meters
z: 0.275     # Meters
yaw: 3.14   # Radians

# Sensor Settings
min_angle: -2.26889 # Radians
max_angle: 2.26889  # Radians
ray_count: 240
range: 10.0         # Meters
